# Generated by Django 4.2.28 on 2026-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, help_text='Location for Offline Workshop', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Specific time for Webinar/Workshop', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('course', 'Pelatihan'), ('webinar', 'Webinar'), ('workshop', 'Workshop')], default='course', max_length=20),
        ),
    ]
