# Generated by Django 4.2.28 on 2026-02-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_userlessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zoom_link',
            field=models.URLField(blank=True, help_text='Zoom Link for Webinar', max_length=500, null=True),
        ),
    ]
