# Generated by Django 4.2.28 on 2026-02-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_certificationalternative_certificationexam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationinstructorslot',
            name='zoom_link',
            field=models.URLField(blank=True, help_text='Zoom/Meeting Link for interview', max_length=500, null=True),
        ),
    ]
