# Generated by Django 4.2.28 on 2026-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_certificationinstructorslot_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_certification_exam',
            field=models.BooleanField(default=False),
        ),
    ]
