# Generated by Django 4.2.28 on 2026-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_course_has_certification_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
