# Generated by Django 4.2.28 on 2026-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, help_text='End date/time for course, webinar, or workshop', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Start date/time for course, webinar, or workshop', null=True),
        ),
    ]
