# Generated by Django 4.2.28 on 2026-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_course_scheduled_end_at_alter_course_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationexam',
            name='confirmed_end_at',
            field=models.DateTimeField(blank=True, help_text='Confirmed end datetime for certification exam', null=True),
        ),
        migrations.AddField(
            model_name='certificationexam',
            name='confirmed_start_at',
            field=models.DateTimeField(blank=True, help_text='Confirmed start datetime for certification exam', null=True),
        ),
    ]
