# Generated by Django 6.0.2 on 2026-04-13 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0025_certificationexam_passing_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='elearning_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='elearning_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='inhouse_training_benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='inhouse_training_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='inhouse_training_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='public_sessions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='public_training_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='public_training_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InhouseTrainingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('position', models.CharField(blank=True, max_length=120, null=True)),
                ('participants_count', models.PositiveIntegerField(default=1)),
                ('preferred_mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('training_goals', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Baru'), ('contacted', 'Sudah Dihubungi'), ('quoted', 'Penawaran Dikirim'), ('closed', 'Selesai')], default='new', max_length=20)),
                ('sales_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhouse_requests', to='academy.course')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
