# Generated by Django 4.2.28 on 2026-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0041_discussion_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentaccesslink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentaccesslinkclaim',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
