# Generated by Django 4.2.28 on 2026-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0044_project_alter_userprofile_staff_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rundown_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instructor',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
