# Generated by Django 4.2.28 on 2026-05-05 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0045_course_rundown_items_instructor_expertise_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationattempt',
            name='interview_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificationattempt',
            name='interview_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificationattempt',
            name='interview_result',
            field=models.CharField(choices=[('PENDING', 'Menunggu Review'), ('PASSED', 'Lolos'), ('FAILED', 'Tidak Lolos')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='certificationattempt',
            name='interview_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationattempt',
            name='interview_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certification_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificationattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='certificationexam',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificationquestion',
            name='category_label',
            field=models.CharField(blank=True, default='Umum', max_length=120),
        ),
        migrations.AddField(
            model_name='certificationquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certification/questions/'),
        ),
    ]
