# Generated by Django 4.2.28 on 2026-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0046_certificationattempt_interview_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/questions/'),
        ),
    ]
