# Generated by Django 4.2.28 on 2026-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0048_order_affiliate_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nik',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
