services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: akademiso-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: akademiso-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
      BACKEND_INTERNAL_URL: "http://backend:8000"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
