services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: akademiso-backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend,72.61.208.187"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: akademiso-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://72.61.208.187:8000"
      BACKEND_INTERNAL_URL: "http://backend:8000"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
